Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, axes = pro.subplots(sharex=0, ncols=2)

labels = [
    "Center of Mass",
    "Peak",
    "DFT (f=1)",
    "DFT (f=10)",
    "Moffat PSF",
    "Gaussian PSF",
    "AiryDisk PSF",
]
offsets = [
    offsets_com,
    offsets_peak,
    offsets_dft,
    offsets_dft_10,
    offsets_moffat,
    offsets_gaussian,
    offsets_airydisk,
]


for label, samples in zip(labels, offsets):
    axes[0].hist(samples[:, 1], bins="auto", fill=False, lw=1, label=label)
    axes[1].hist(samples[:, 0], bins="auto", fill=False, lw=1)
axes[0].format(xlabel=r"$\Delta$x (mas)", ylabel="count")
axes[1].format(xlabel=r"$\Delta$y (mas)")
axes.dualx(lambda a: a / 6.24, label="(px)")
fig.format(suptitle="AB Aurigae 2019/03/20 Non-coronagraphic")
fig.legend(loc="bottom", ncols=4);
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
Cell [0;32mIn[6], line 24[0m
[1;32m     12[0m offsets [38;5;241m=[39m [
[1;32m     13[0m     offsets_com,
[1;32m     14[0m     offsets_peak,
[0;32m   (...)[0m
[1;32m     19[0m     offsets_airydisk,
[1;32m     20[0m ]
[1;32m     23[0m [38;5;28;01mfor[39;00m label, samples [38;5;129;01min[39;00m [38;5;28mzip[39m(labels, offsets):
[0;32m---> 24[0m     axes[[38;5;241m0[39m][38;5;241m.[39mhist([43msamples[49m[43m[[49m[43m:[49m[43m,[49m[43m [49m[38;5;241;43m1[39;49m[43m][49m, bins[38;5;241m=[39m[38;5;124m"[39m[38;5;124mauto[39m[38;5;124m"[39m, fill[38;5;241m=[39m[38;5;28;01mFalse[39;00m, lw[38;5;241m=[39m[38;5;241m1[39m, label[38;5;241m=[39mlabel)
[1;32m     25[0m     axes[[38;5;241m1[39m][38;5;241m.[39mhist(samples[:, [38;5;241m0[39m], bins[38;5;241m=[39m[38;5;124m"[39m[38;5;124mauto[39m[38;5;124m"[39m, fill[38;5;241m=[39m[38;5;28;01mFalse[39;00m, lw[38;5;241m=[39m[38;5;241m1[39m)
[1;32m     26[0m axes[[38;5;241m0[39m][38;5;241m.[39mformat(xlabel[38;5;241m=[39m[38;5;124mr[39m[38;5;124m"[39m[38;5;124m$[39m[38;5;124m\[39m[38;5;124mDelta$x (mas)[39m[38;5;124m"[39m, ylabel[38;5;241m=[39m[38;5;124m"[39m[38;5;124mcount[39m[38;5;124m"[39m)

[0;31mIndexError[0m: index 1 is out of bounds for axis 1 with size 1
IndexError: index 1 is out of bounds for axis 1 with size 1

