Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from vampires_dpp.pipeline import Pipeline

pipeline = Pipeline.from_file(datadir / "hd36819_20220128_config.toml")
pipeline.run()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[3], line 3[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mvampires_dpp[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpipeline[39;00m [38;5;28;01mimport[39;00m Pipeline
[0;32m----> 3[0m pipeline [38;5;241m=[39m [43mPipeline[49m[38;5;241;43m.[39;49m[43mfrom_file[49m[43m([49m[43mdatadir[49m[43m [49m[38;5;241;43m/[39;49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mhd36819_20220128_config.toml[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      4[0m pipeline[38;5;241m.[39mrun()

File [0;32m/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/vampires_dpp/pipeline.py:111[0m, in [0;36mPipeline.from_file[0;34m(cls, filename)[0m
[1;32m     92[0m [38;5;129m@classmethod[39m
[1;32m     93[0m [38;5;28;01mdef[39;00m [38;5;21mfrom_file[39m([38;5;28mcls[39m, filename: PathLike):
[1;32m     94[0m     [38;5;124;03m"""[39;00m
[1;32m     95[0m [38;5;124;03m    Load configuration from TOML file[39;00m
[1;32m     96[0m 
[0;32m   (...)[0m
[1;32m    109[0m [38;5;124;03m    >>> Pipeline.from_file("config.toml")[39;00m
[1;32m    110[0m [38;5;124;03m    """[39;00m
[0;32m--> 111[0m     config [38;5;241m=[39m [43mtoml[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[43mfilename[49m[43m)[49m
[1;32m    112[0m     [38;5;28;01mreturn[39;00m [38;5;28mcls[39m(config)

File [0;32m/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/toml/decoder.py:133[0m, in [0;36mload[0;34m(f, _dict, decoder)[0m
[1;32m    114[0m [38;5;124;03m"""Parses named file or files as toml and returns a dictionary[39;00m
[1;32m    115[0m 
[1;32m    116[0m [38;5;124;03mArgs:[39;00m
[0;32m   (...)[0m
[1;32m    129[0m [38;5;124;03m    (Python 2 / Python 3)          file paths is passed[39;00m
[1;32m    130[0m [38;5;124;03m"""[39;00m
[1;32m    132[0m [38;5;28;01mif[39;00m _ispath(f):
[0;32m--> 133[0m     [38;5;28;01mwith[39;00m [43mio[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43m_getpath[49m[43m([49m[43mf[49m[43m)[49m[43m,[49m[43m [49m[43mencoding[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mutf-8[39;49m[38;5;124;43m'[39;49m[43m)[49m [38;5;28;01mas[39;00m ffile:
[1;32m    134[0m         [38;5;28;01mreturn[39;00m loads(ffile[38;5;241m.[39mread(), _dict, decoder)
[1;32m    135[0m [38;5;28;01melif[39;00m [38;5;28misinstance[39m(f, [38;5;28mlist[39m):

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'data/hd36819_20220128/hd36819_20220128_config.toml'
FileNotFoundError: [Errno 2] No such file or directory: 'data/hd36819_20220128/hd36819_20220128_config.toml'

